import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { root, trackedFiles } from "./inventory.mjs";

export function conventionalRole(path) {
  const name = path.split("/").at(-1);
  if (name === "package-lock.json") return "npm dependency lockfile; generated by npm.";
  if (name === "package.json") return "Web package scripts, dependency versions and runtime constraints.";
  if (name === ".gitignore") return "Version-control exclusions for secrets, build output and local artifacts.";
  if (name === ".npmrc") return "Exact dependency saves; automatic install audits disabled for phase-end cadence.";
  if (name === ".editorconfig") return "Editor whitespace and encoding conventions.";
  if (name === ".nvmrc") return "Supported Node LTS major.";
  return undefined;
}
export function renderMap(files, roles) {
  const missing = files.filter((p) => !roles[p] && !conventionalRole(p));
  const stale = Object.keys(roles).filter((p) => !files.includes(p));
  if (missing.length || stale.length) throw new Error(`Missing roles: ${missing.join(", ")}; stale roles: ${stale.join(", ")}`);
  const rows = [...files].sort().map((p) => `| \`${p}\` | ${(roles[p] ?? conventionalRole(p)).replaceAll("|", "\\|")} |`);
  return ["# Codebase map", "", "Generated inventory from Git; authored roles live in `scripts/map-roles.json`.",
    "Run `node scripts/codebase-map.mjs --write` after staging added/removed paths.", "",
    "`apps/web` owns the web shell; `agent` owns the CLI; `infra` owns service assets;",
    "`scripts` owns local gates; `docs` owns human-facing contracts. The web API owns operator access and initial enrollment.", "",
    "| Tracked path | Role |", "| --- | --- |", ...rows, ""].join("\n");
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const files = trackedFiles();
  for (const file of files) if (!existsSync(resolve(root, file))) throw new Error(`Missing file: ${file}`);
  const roles = JSON.parse(readFileSync(resolve(root, "scripts/map-roles.json"), "utf8"));
  const expected = renderMap(files, roles);
  const target = resolve(root, "docs/architecture/codebase-map.md");
  if (process.argv.includes("--write")) writeFileSync(target, expected);
  else if (readFileSync(target, "utf8") !== expected) throw new Error("Codebase map is stale");
  console.log(`Codebase map valid: ${files.length} tracked paths`);
}
